# ================================================================
# NavGeo - Configuración de la Aplicación
# ================================================================

spring.application.name=NavGeo
spring.profiles.active=local
google.maps.api-key=AIzaSyBQioA2hGEBbcoB9I98gjwL8fF-Uv8QhME

# ================================================================
# BASE DE DATOS - PostgreSQL
# ================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/navgeo_db
spring.datasource.username=postgres
spring.datasource.password=11031416&
spring.datasource.driver-class-name=org.postgresql.Driver

# permititr

# Configuración de Google OAuth2 para desarrollo local
spring.security.oauth2.client.registration.google.client-id=542668873578-vdprl5dv54sg0g2p0b60rmr2ilv9tqnp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# ================================================================
# SERVIDOR
# ================================================================
server.port=8080


# SSL deshabilitado en desarrollo local
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=localhost
server.ssl.key-store-password=11031416&

# Sesión y timeouts
server.servlet.session.timeout=60m
spring.mvc.async.request-timeout=120000

# Tamaño máximo del request para rutas con muchos puntos
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.max-file-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

# ================================================================
# JPA / HIBERNATE
# ================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

# ================================================================
# THYMELEAF
# ================================================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ================================================================
# LOGGING
# ================================================================
logging.level.com.navgeo=DEBUG
logging.level.org.springframework.security=INFO
