

# --- Servidor ---
server.port=8080

spring.application.name=NavGeo

spring.profiles.active=local

google.maps.api-key=${GOOGLE_MAPS_API_KEY:}

spring.datasource.url=jdbc:postgresql://localhost:5432/navgeo_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Inicialización con script SQL (se ejecuta al arrancar si ddl-auto=validate/none) ---
spring.sql.init.mode=never

# ================================================================
# CONFIGURACIÓN DE THYMELEAF
# ================================================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ================================================================
# LOGGING
# ================================================================
logging.level.com.navgeo=DEBUG
logging.level.org.springframework.security=INFO
